p = pair<goose,double>(goose(15),3.1)
v = vector<goose>([goose(0),goose(3),goose(4)])
vp = vector<goose*>([goose(1),goose(15)])
vcp = vector<const goose*>([goose(0),goose(5)])
l = list<goose>([goose(1),goose(2),goose(3)])
lp = list<goose*>([goose(0),goose(4),goose(5)])
lcp = list<const goose*>([goose(11)])
str_map = map<goose,string>({goose(5) => "two", goose(15) => "one"})
bot_map = map<goose,bottle>({goose(0) => bottle("three")})
bot_ptr_map = map<goose,bottle*>({goose(4) => bottle("4"), goose(5) => bottle("5")})
bot_cptr_map = map<goose,const bottle*>({goose(6) => bottle("6"), goose(7) => bottle("7")})
;
p = pair<goose,double>(goose(15),3.1)
v = vector<goose>([goose(3),goose(3),goose(3)])
vp = vector<goose*>([goose(1)])
vcp = vector<const goose*>([])
l = list<goose>([])
lp = list<goose*>([goose(NULL),goose(NULL),goose(NULL)])
lcp = list<const goose*>([goose(1),goose(1),goose(1),goose(1)])
str_map = map<goose,string>({goose(5) => "two", goose(15) => "one"})
bot_map = map<goose,bottle>({})
bot_ptr_map = map<goose,bottle*>({goose(4) => bottle(NULL), goose(5) => bottle(NULL)})
bot_cptr_map = map<goose,const bottle*>({goose(6) => bottle("6"), goose(7) => bottle("7")})
;
